#once

; **********************************************************
; THE STARTING ADDRESS OF THE FORTH MEMORY
#const F_MEMORY_START = 0xB000
; THE MAX SIZE OF A SINGLE INPUT (64 bytes -> up to 256)
#const F_MAX_INPUT_SIZE = 0x40
; THE MAX SIZE OF THE STACK
#const F_MAX_STACK_SIZE = 0xFF
; THE MAX SIZE OF THE DICTIONARY (built-in + user)
#const F_MAX_DICT_SIZE = 0x1000 ; 4K
; **********************************************************

; **********************************************************
; MEMORY OFFSETS
#const F_INPUT_BUFFER_START = F_MEMORY_START + 0x0000
#const F_INPUT_BUFFER_END = F_MEMORY_START + 0x00FF
#const F_INPUT_BUFFER_COUNT = F_MEMORY_START + 0x0100
#const F_TOKEN_START = F_MEMORY_START + 0x0101
#const F_TOKEN_COUNT = F_MEMORY_START + 0x0102
#const F_TOKEN_VALUE= F_MEMORY_START + 0x0103
#const F_STACK_COUNT = F_MEMORY_START + 0x0104

#const F_DICT_ADD_BUFFER_START = F_MEMORY_START + 0x0105
#const F_DICT_ADD_BUFFER_END = F_MEMORY_START + 0x011A

#const F_DICT_ADD_BUILT_IN_LABEL_PTR_LSB = F_MEMORY_START + 0x011B
#const F_DICT_ADD_BUILT_IN_LABEL_PTR_MSB = F_MEMORY_START + 0x011C
#const F_DICT_ADD_BUILT_IN_PTR_LSB = F_MEMORY_START + 0x011D
#const F_DICT_ADD_BUILT_IN_PTR_MSB = F_MEMORY_START + 0x011E

#const F_DICT_EXEC_BUILT_IN_PTR_PAGE = F_MEMORY_START + 0x011F
#const F_DICT_EXEC_BUILT_IN_PTR_MSB  = F_MEMORY_START + 0x0120
#const F_DICT_EXEC_BUILT_IN_PTR_LSB  = F_MEMORY_START + 0x0121

#const F_EXIT_INTERPRETER_FLAG = F_MEMORY_START + 0x0122
#const F_EXECUTION_ERROR_FLAG = F_MEMORY_START + 0x0123

#const F_DICT_ADD_USER_START = F_MEMORY_START + 0x0124
#const F_DICT_ADD_USER_COUNT = F_MEMORY_START + 0x0125

#const F_DICT_EXEC_USER_ITEM = F_MEMORY_START + 0x0126
#const F_STATUS_COUNT = F_MEMORY_START + 0x0127

#const F_FIND_TOKEN_MSB = F_MEMORY_START + 0x0128
#const F_FIND_TOKEN_LSB = F_MEMORY_START + 0x0129
#const F_FIND_TOKEN_START = F_MEMORY_START + 0x012A
#const F_FIND_TOKEN_COUNT = F_MEMORY_START + 0x012B

#const F_BI_IF_THEN_START = F_MEMORY_START + 0x012C
#const F_BI_IF_ELSE_START = F_MEMORY_START + 0x012D

#const F_DICT_BUILT_IN_COUNT = F_MEMORY_START + 0x012E
#const F_DICT_USER_START_LSB = F_MEMORY_START + 0x012F
#const F_DICT_USER_START_MSB = F_MEMORY_START + 0x0130
#const F_DICT_USER_COUNT = F_MEMORY_START + 0x0131

; Placing the stack at the end of the variable area
#const F_STACK_START = F_MEMORY_START + 0x0200

; Placing the dictionary at the end of the stack area 
; The user dictionary is placed at the end of the buil-in dictionary
#const F_DICT_BUILT_IN_START = F_STACK_START + F_MAX_STACK_SIZE

; Placing the status saving area at the end of the dictionary 
#const F_STATUS_START = F_DICT_BUILT_IN_START + F_MAX_DICT_SIZE 

; **********************************************************