#!/usr/bin/env bash
# Build / flash OttoTerminal (ESP32 + FabGL VGATextController) for Project Otto.
#
# Target board: LilyGO TTGO T7 Mini32 v1.4 (VGA32, ESP32-WROVER + PSRAM)
#
# Prerequisites:
#   - Arduino ESP32 core 2.0.17 (esp32:esp32)
#     arduino-cli core install esp32:esp32@2.0.17
#   - FabGL library in ~/Documents/Arduino/libraries/FabGL
#   - arduino-cli on PATH, or Arduino IDE 2.x installed
#   - `python` on PATH (symlink to python3); build.sh tries to fix this on macOS
#
# Usage:
#   ./devices/vga32/build.sh              # compile OttoTerminal
#   ./devices/vga32/build.sh compile
#   ./devices/vga32/build.sh upload       # compile + flash
#   ./devices/vga32/build.sh bump minor   # 1.0.5 -> 1.1.0 (patch reset)
#   ./devices/vga32/build.sh bump major   # 1.1.0 -> 2.0.0
#   ./devices/vga32/build.sh bump patch   # bump patch without compiling
#
# Versioning (SemVer 2.0):
#   OttoTerminal/otto_version.txt — MAJOR.MINOR.PATCH
#   Each compile/upload increments PATCH (unless OTTO_SKIP_VERSION_BUMP=1)
#   Use bump minor|major for intentional release bumps
#
# Environment (override defaults):
#   FQBN          Board FQBN (default: esp32wrover huge_app)
#   PORT          USB serial port for upload

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKETCH="${SCRIPT_DIR}/OttoTerminal"

VER_FILE="${SKETCH}/otto_version.txt"
GEN_FILE="${SKETCH}/otto_version_gen.h"

FQBN="${FQBN:-esp32:esp32:esp32wrover:PartitionScheme=huge_app,UploadSpeed=460800}"
PORT="${PORT:-/dev/cu.usbserial-5B212326931}"

export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"
if ! command -v python >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
  mkdir -p "${HOME}/.local/bin"
  ln -sf "$(command -v python3)" "${HOME}/.local/bin/python" 2>/dev/null || true
  export PATH="${HOME}/.local/bin:${PATH}"
fi

find_arduino_cli() {
  if command -v arduino-cli >/dev/null 2>&1; then
    command -v arduino-cli
    return 0
  fi
  local bundled="/Applications/Arduino IDE.app/Contents/Resources/app/lib/backend/resources/arduino-cli"
  if [[ -x "$bundled" ]]; then
    echo "$bundled"
    return 0
  fi
  echo "arduino-cli not found. Install arduino-cli or Arduino IDE 2.x." >&2
  exit 1
}

ARDUINO_CLI="$(find_arduino_cli)"

read_semver() {
  local raw="1.0.0"
  if [[ -f "$VER_FILE" ]]; then
    raw=$(tr -d '[:space:]' < "$VER_FILE")
  fi
  if [[ ! "$raw" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid semver in ${VER_FILE}: '${raw}' (expected MAJOR.MINOR.PATCH)" >&2
    exit 1
  fi
  IFS='.' read -r OTTO_VER_MAJ OTTO_VER_MIN OTTO_VER_PAT <<< "$raw"
}

write_semver() {
  printf '%s.%s.%s\n' "$OTTO_VER_MAJ" "$OTTO_VER_MIN" "$OTTO_VER_PAT" > "$VER_FILE"
}

write_version_gen() {
  cat > "$GEN_FILE" <<EOF
// Auto-generated by devices/vga32/build.sh — do not edit.
#pragma once

#define OTTO_APP_VERSION_MAJ ${OTTO_VER_MAJ}
#define OTTO_APP_VERSION_MIN ${OTTO_VER_MIN}
#define OTTO_APP_VERSION_PAT ${OTTO_VER_PAT}
#define OTTO_APP_VERSION     "${OTTO_VER_MAJ}.${OTTO_VER_MIN}.${OTTO_VER_PAT}"
EOF
}

bump_patch_for_build() {
  read_semver
  if [[ "${OTTO_SKIP_VERSION_BUMP:-0}" != "1" ]]; then
    OTTO_VER_PAT=$((OTTO_VER_PAT + 1))
    write_semver
  fi
  write_version_gen
  echo "   version: ${OTTO_VER_MAJ}.${OTTO_VER_MIN}.${OTTO_VER_PAT}"
}

bump_semver() {
  local part="${1:-}"
  if [[ "$part" != patch && "$part" != minor && "$part" != major ]]; then
    echo "Usage: $0 bump patch|minor|major" >&2
    exit 1
  fi

  read_semver
  case "$part" in
    patch)
      OTTO_VER_PAT=$((OTTO_VER_PAT + 1))
      ;;
    minor)
      OTTO_VER_MIN=$((OTTO_VER_MIN + 1))
      OTTO_VER_PAT=0
      ;;
    major)
      OTTO_VER_MAJ=$((OTTO_VER_MAJ + 1))
      OTTO_VER_MIN=0
      OTTO_VER_PAT=0
      ;;
  esac
  write_semver
  write_version_gen
  echo "-> semver now ${OTTO_VER_MAJ}.${OTTO_VER_MIN}.${OTTO_VER_PAT}"
}

compile() {
  bump_patch_for_build
  echo "-> compile ${SKETCH}"
  echo "   board: LilyGO TTGO T7 Mini32 v1.4 (ESP32 Wrover)"
  echo "   fqbn:  ${FQBN}"
  "$ARDUINO_CLI" compile --fqbn "$FQBN" "$SKETCH"
}

upload() {
  local port="${1:-${PORT}}"
  if [[ -z "$port" ]]; then
    echo "Serial port required for upload." >&2
    echo "Usage: $0 upload [PORT]" >&2
    exit 1
  fi
  if [[ ! -e "$port" ]]; then
    echo "Warning: serial port not found: ${port}" >&2
    echo "         plug in the TTGO or set PORT=... before upload." >&2
  fi
  compile
  echo "-> upload to ${port}"
  "$ARDUINO_CLI" upload -p "$port" --fqbn "$FQBN" "$SKETCH"
}

case "${1:-compile}" in
  compile)
    compile
    ;;
  upload|flash|build)
    upload "${2:-}"
    ;;
  bump)
    bump_semver "${2:-}"
    ;;
  -h|--help|help)
    sed -n '2,27p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  *)
    echo "Unknown command: $1" >&2
    echo "Run: $0 help" >&2
    exit 1
    ;;
esac
