; @load-address 0x020000
;==========================================================
; Otto Disassembler - standalone tool
; Disassembles memory at any 24-bit address
; Loads at 0x020000 (expansion RAM page 2) to avoid
; overwriting apps at 0x8400
;
; Usage: enter hex address (4 or 6 digits), Enter to
;        continue, 'q' to quit
;==========================================================

#include "../assembly/ruledef.asm"
#include "../kernel/symbols.asm"

#bankdef ram
{
    #addr 0x020000
    #size 0x10000
    #outp 0
}

#bank ram
    jmp disasm

; --- Instruction description table (autogenerated) ---
#include "istructions.asm"

; --- All code and data under one non-local label for local label scoping ---
disasm:
    ldy .banner[23:16]
    ldd .banner[15:8]
    lde .banner[7:0]
    jsr .send_string

    lda 0x00
    sta .addr_page
    lda 0x84
    sta .addr_msb
    lda 0x00
    sta .addr_lsb

.main_loop:
    jsr ACIA_SEND_NEWLINE
    ldy .prompt[23:16]
    ldd .prompt[15:8]
    lde .prompt[7:0]
    jsr .send_string

    lda 0x00
    sta .input_count

.read_char:
    jsr ACIA_READ_CHAR

    cmp 0x0D
    beq .input_done

    cmp "q"
    beq .quit
    cmp "Q"
    beq .quit

    cmp 0x7F
    beq .backspace
    cmp 0x08
    beq .backspace

    jsr ACIA_SEND_CHAR

    ldx .input_count
    sta .input_buffer,x
    inc .input_count

    cpx 0x05
    beq .input_done

    jmp .read_char

.backspace:
    lda .input_count
    beq .read_char
    dec .input_count
    jsr VT100_CURSOR_LEFT
    jsr VT100_CLEAR_LINE_END
    jmp .read_char

.input_done:
    lda .input_count
    beq .use_current

    cmp 0x04
    beq .parse_4
    cmp 0x06
    beq .parse_6

    ldy .error_msg[23:16]
    ldd .error_msg[15:8]
    lde .error_msg[7:0]
    jsr .send_string
    jmp .main_loop

.parse_6:
    lda .input_buffer
    ldx .input_buffer + 1
    jsr HEXBIN
    sta .addr_page

    lda .input_buffer + 2
    ldx .input_buffer + 3
    jsr HEXBIN
    sta .addr_msb

    lda .input_buffer + 4
    ldx .input_buffer + 5
    jsr HEXBIN
    sta .addr_lsb
    jmp .use_current

.parse_4:
    lda 0x00
    sta .addr_page

    lda .input_buffer
    ldx .input_buffer + 1
    jsr HEXBIN
    sta .addr_msb

    lda .input_buffer + 2
    ldx .input_buffer + 3
    jsr HEXBIN
    sta .addr_lsb

.use_current:
    lda 0x00
    sta .dump_count

.disasm_instruction:
    jsr .load_address
    jsr ACIA_SEND_NEWLINE

    tya
    jsr ACIA_SEND_HEX
    tda
    jsr ACIA_SEND_HEX
    tea
    jsr ACIA_SEND_HEX
    lda 0x3a
    jsr ACIA_SEND_CHAR
    lda 0x20
    jsr ACIA_SEND_CHAR

    ldx 0x00
    lda yde,x
    pha

    jsr ACIA_SEND_HEX
    lda 0x20
    jsr ACIA_SEND_CHAR

    jsr .inc_address

    plx
    lda ISTRUCTIONS.OPCODE_MSB, x
    tad
    lda ISTRUCTIONS.OPCODE_LSB, x
    tae

    std .opcode_msb
    ste .opcode_lsb

    ldy ISTRUCTIONS[23:16]
    ldx 0x00
    lda yde,x
    sta .opcode_length
    inx
    lda yde,x
    sta .opcode_length_2

    jsr .load_address
    ldx 0x00

.dump_value:
    cpx .opcode_length
    beq .dump_value_end

    lda yde,x
    phx
    jsr ACIA_SEND_HEX
    lda 0x20
    jsr ACIA_SEND_CHAR
    plx
    inx
    jmp .dump_value

.dump_value_end:
    ldx 0x04
.dump_value_pad:
    cpx .opcode_length
    beq .print_prefix
    lda 0x20
    jsr ACIA_SEND_CHAR
    jsr ACIA_SEND_CHAR
    jsr ACIA_SEND_CHAR
    dex
    jmp .dump_value_pad

.print_prefix:
    ldd .opcode_msb
    lde .opcode_lsb
    ldy ISTRUCTIONS[23:16]
    ldx 0x02

.print_prefix_loop:
    lda yde,x
    beq .print_prefix_end
    jsr ACIA_SEND_CHAR
    inx
    jmp .print_prefix_loop

.print_prefix_end:
    inx
    stx .opcode_ptr

    lda .opcode_length_2
    beq .print_suffix

    jsr .load_address
    ldx 0x00

    lda 0x20
    jsr ACIA_SEND_CHAR
    lda "0"
    jsr ACIA_SEND_CHAR
    lda "x"
    jsr ACIA_SEND_CHAR

.print_value_loop:
    cpx .opcode_length_2
    beq .print_value_end

    lda yde,x
    phx
    jsr ACIA_SEND_HEX
    plx
    inx
    jmp .print_value_loop

.print_value_end:
    lda 0x20
    jsr ACIA_SEND_CHAR

.print_suffix:
    ldd .opcode_msb
    lde .opcode_lsb
    ldy ISTRUCTIONS[23:16]
    ldx .opcode_ptr

.print_suffix_loop:
    lda yde,x
    beq .advance_address
    jsr ACIA_SEND_CHAR
    inx
    jmp .print_suffix_loop

.advance_address:
    lda .opcode_length
    beq .next_instr
    jsr .inc_address
    dec .opcode_length
    jmp .advance_address

.next_instr:
    inc .dump_count
    lda .dump_count
    cmp 0x0a
    bne .disasm_instruction
    jmp .main_loop

.quit:
    jsr ACIA_SEND_NEWLINE
    rts

; --- Helpers ---

.send_string:
    ldx 0x00
.send_string_loop:
    lda yde,x
    beq .send_string_end
    jsr ACIA_SEND_CHAR
    inx
    bne .send_string_loop
    ind
    jmp .send_string_loop
.send_string_end:
    rts

.load_address:
    ldy .addr_page
    ldd .addr_msb
    lde .addr_lsb
    rts

.inc_address:
    inc .addr_lsb
    bne .inc_address_end
    inc .addr_msb
    bne .inc_address_end
    inc .addr_page
.inc_address_end:
    rts

; --- Strings ---

.banner:
    #d 0x0A, 0x0D
    #d "Otto Disassembler v1.0", 0x0A, 0x0D
    #d "Enter address (4/6 hex digits), Enter=continue, q=quit", 0x0A, 0x0D
    #d 0x00

.prompt:
    #d "addr> ", 0x00

.error_msg:
    #d 0x0A, 0x0D, "?use 4 or 6 hex digits", 0x0A, 0x0D, 0x00

; --- Variables ---
.addr_page:       #d 0x00
.addr_msb:        #d 0x84
.addr_lsb:        #d 0x00
.opcode_msb:      #d 0x00
.opcode_lsb:      #d 0x00
.opcode_length:   #d 0x00
.opcode_length_2: #d 0x00
.opcode_ptr:      #d 0x00
.dump_count:      #d 0x00
.input_count:     #d 0x00
.input_buffer:    #d 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
